### ISSUE TITLE
Executor ColorShifter 

### ISSUE THREAD

**Issue by to92me** [bstaletic/eurobot2k17#11]
propose API and implement executor.

**Comment by bstaletic** [comment]
What kind of motor will this use?

Proposed api:

- `rotate(direction, relative_degrees)`
- `stop()`
- something for moving it to and from the tube that is being (should be) rotated

All of these name are subject to change and are a simple proposals.

**Comment by darko31** [comment]
ColorShifter will be a simple DC motor, or maybe AX-12. It's job is to spin the lunar module until the right color is matched with the sensor.

So maybe, there's no need for direction, an there is no way of counting degrees. I think that proposed API could be only

start/stop

but this executor should be somehow linked with Color sensor for rotating until blue or yellow colors are detected, then stopping.

**Comment by bstaletic** [comment]
> So maybe, there's no need for direction, an there is no way of counting degrees. I think that proposed API could be only
>
>start/stop

Alright, that simplifies things quite a bit. As for direction, we might be more efficient if we can somehow determine in which direction should the motor rotate, but that requires quite a bit more testing.

> this executor should be somehow linked with Color sensor

That should not be an issue. Executors are supposed to use drivers internally.
Should we read the color sensor periodically starting at the moment the DC motor starts rotating?

**Comment by to92me** [comment]
Maybe API of executor should be something like this: 

``` void shift(Color _color); ```

and rotation and color checking should be implemented in the executor?

**Comment by darko31** [comment]
@bstaletic 
Yeah, pooling will do fine for this task, this won't be something crazy fast. 
@to92me 
Sounds good.

**Comment by bstaletic** [comment]
Closed by #34
