### ISSUE TITLE
Executor Door

### ISSUE THREAD

**Issue by to92me** [bstaletic/eurobot2k17#12]
propose API and implement executor.

**Comment by darko31** [comment]
Remind me again, what it windows executor supposed to do?

**Comment by bstaletic** [comment]
This should be used for unloading tubes sideways and into the smaller placeholder.

**Comment by darko31** [comment]
Oh, okay, again two analog servos, one for sliding the tubes from the revolver, and one for opening window.

**Comment by bstaletic** [comment]
Solved by #38
