### ISSUE TITLE
Executor Trunk

### ISSUE THREAD

**Issue by to92me** [bstaletic/eurobot2k17#13]
propose API and implement executor.

----
operations: 
1. open 
2. close 
3. increase 
4. reduce

**Comment by bstaletic** [comment]
I believe @darko31 said these should be handeled with two separate analog servo motors, but I think we should wait for him to confirm that.

**Comment by darko31** [comment]
Yeah, two separate analog servos. One for open/close, one for increase/reduce.

**Comment by bstaletic** [comment]
Closed by #25
