### ISSUE TITLE
UART4 ISR() not currently working

### ISSUE THREAD

**Issue by bstaletic** [bstaletic/eurobot2k17#15]
The `usart2_isr()` is not working currently, as it requires connecting to the nested vectored interrupt controller. For that we need at least `nvic.h` included and `nvic_enable_irq(NVIC_USART2_IRQ);` called.

**Comment by darko31** [comment]
Okay, should this be in basic functionality? It isn't yet implemented in motion driver on the PIC?

Maybe implementing pooling method until we test out this on the PIC?

**Comment by bstaletic** [comment]
I put it in the "basic functionality" because a non-working version is already in this repo.

If you think this should be removed from "basic functionality", I would have no problem with that. I just hate having non-working code inside a repo.

**Comment by darko31** [comment]
Yeah, okay, this shouldn't be too hard to implement, leave it  basic.

**Comment by bstaletic** [comment]
The `nvic_enable_irq(NVIC_USART2_IRQ)` should really be called in `usart2_config()`, as that is the only sane place to call it. That makes me not like placing thte ISR in `motion.c`.

@to92me @darko31 What do you think, should we move the ISR to `uart_config.c`?

**Comment by darko31** [comment]
Yeah, sure

**Comment by bstaletic** [comment]
Since this was my mess, I'll clean it up. Self-assigned.

**Comment by to92me** [comment]
>The nvic_enable_irq(NVIC_USART2_IRQ) should really be called in usart2_config(), as that is the only sane place to call it. That makes me not like placing thte ISR in motion.c.

@bstaletic  i agree
