### ISSUE TITLE
Motion driver - Add "kurva" 

### ISSUE THREAD

**Issue by to92me** [bstaletic/eurobot2k17#5]
Patch motion driver with "kurva" method :D. 

**Note:  This is not priority !!**

**Comment by bstaletic** [comment]
Just a comment, as I agree that this is not a priority.

It is definitely easy to implement this into the driver, as the only thing needed would be one function in [`motion.c`](https://github.com/bstaletic/eurobot2k17/blob/master/src/drivers/actuators/motion/motion.c). This was skipped as I couldn't remember of the top of my head what was the correct order of parameters needed.

**Comment by darko31** [comment]
Params for kurva are:

int16 x
int16 y
int8 angle
int8 angle_directon
int8 direction_of_robot //dupe, glava

**Comment by bstaletic** [comment]
>int16
>int8

Are these `int`s, or `uint`s (i.e. are these signed)?

**Comment by darko31** [comment]
x, y and angle are signed.
angle_direction, direction_of_robot are chars

**Comment by to92me** [comment]
@darko31 could you maybe create some file with api of motion board ? In wiki or somewhere ? Nothing special some gibberish doc

**Comment by darko31** [comment]
I will. It's pretty much done, @bstaletic wrote it right, just checked it. Only MSB and LSB for int16 are in reverse, he'll patch it soon.
