### ISSUE TITLE
Executor Revolver

### ISSUE THREAD

**Issue by to92me** [bstaletic/eurobot2k17#8]
propose API and implement executor.

**Comment by darko31** [comment]
Now this should be fun. One AX-12 servo has 0 to 300 degrees operating angle (0 to 1024 for angle parameter). The plan is to have 8 positions and different ratio tooth belt pulleys for a full 360 degrees angle range for the revolver.

We can calibrate the positions when we make the mechanism, so we know exactly at what position is the revolver lined up with the sponges at the bottom. Also we can test exactly how much of rotation is needed to switch positions. 

Proposed API
go_to_position(position_number)  //also there should be some way of tracking which tube is at which position
next()  //rotate for angle to next positon
previous()

**Comment by bstaletic** [comment]
We could also make AX12 rotate for more than 300 degrees without going into qheel/joint (whatever it is called) mode. Would this be useful?

**Comment by darko31** [comment]
No, it loses its position when its in wheel mode.

**Comment by bstaletic** [comment]
I am aware of that. But we could make it rotate for, let's say, 350 degrees and **not** go into wheel mode. Would that provide any advantage?

**Comment by darko31** [comment]
I don't think that will work. There is physical deadspot in the potentiometer between 300 and 360/0 degrees. It just wouldn't know its position.

**Comment by ivar94** [comment]
Having a different ratio tooth belt pulleys could work amazing, and it could just allow us more space inside the robot. Question is, where will we find appropriate belt?

**Comment by darko31** [comment]
There's a lot of belts in Memristor's cabinet, most are T5 it think.

**Comment by bstaletic** [comment]
Solved by #24
