### ISSUE TITLE
Executor Front roller

### ISSUE THREAD

**Issue by to92me** [bstaletic/eurobot2k17#9]
propose API and implement executor.

**Comment by darko31** [comment]
Sponge would be two DC motors or hacked analog servo motors. For DC motor, external H-bridge is needed, so one PWM output (can be used from analog servos API), and one or two digital outputs (8 and more are available) for selecting direction of spinning, Two DC motors will be connected in parallel, so they are controlled by the same H bridge.

Proposed API: 
- spin (direction)
- stop()
- set_PWM(value)

**Comment by ivar94** [comment]
This needs also two additional (servo) motors, witch would "squeeze" the cylinder we are trying to get, or this belongs to another executor issue?
Applying two DC motors would not be hard, one PWM output and one H-bridge as darko31 explained, but do we have those motors?

**Comment by darko31** [comment]
No we don't, but we will get them. I think that maybe we won't need additional motors to squeeze the tubes, the prototype worked without them.

**Comment by bstaletic** [comment]
@darko31 
How accurate was the prototype? Should we expect changes when the actual mechanism is constructed?

**Comment by ivar94** [comment]
@darko31 ok, that would be nice.
As for additional motors, if we set the sponges to suck in the tubes, afterwards we need to position them to get the tubes out of revolver into placeholders, I'm missing the picture how will that work if we don't have additional motors just to position the sponges?
If we set the sponge so they can easily get the tubes in es they get them out I think they will get in the way of revolver and it wont rotate easily. It would be great if that can be arranged without additional motors, but lets not risk it, lets include the option of having them?

**Comment by to92me** [comment]
@darko31  @bstaletic  If there is possibility of additional execution I think we should create API for it but  not implement anything until it is required.

**Comment by bstaletic** [comment]
@to92me 
That sounds completely reasonable.

**Comment by darko31** [comment]
I'm not sure that mechanism with additional servos will be strong enough to hold the arms with sponges in place, especially if we use analog servos.  I'm not too happy if we have crappy dangling arms like last year.

The final mechanism should not change from the prototype. Two sponge motors in front for sucking in the tubes. 

For ejecting tubes from the revolver there should be, one additional servo behind the revolver that nudges the tube a bit to the sponges (which are now spinning in reverse).

**Comment by ivar94** [comment]
@darko31 ok, ok, that is cool. Hope there will be enough space for all that inside the robot.
@to92me making those additional API's  (without implementing them) is not a big task, something like set_servo_position(take_in/take_out) where take_in is position where sponges need to be to take the tubes in and vice versa, so lets have it just in case, just in case we need to zbudziti it.

**Comment by bstaletic** [comment]
This is not yet merged, so we shouldn't close the issue just yet.

**Comment by ivar94** [comment]
@bstaletic yea, sorry, my bad
